### ISSUE TITLE
request.onJson callback invocation on error

### ISSUE THREAD

**Issue by disruptek** [cainus/percolator#92]
Invalid JSON, when passed as input in a request, does not cause the callback argument to `onJson` to be invoked -- with or without an error value.  I would expect the callback to be invoked in any event.  Is this working as intended?

This test is verbatim from #91 ...

Here's an example handler:

``` coffeescript
class Test
    POST: (request, response) ->
        console.log 'calling onJson'
        request.onJson (error, input) ->
            console.log 'onJson callback invoked'
            return console.log error if error
            response.object({onJson: input}).send()


exports.handler = new Test()
```

And here's an example test:

``` console
curl -X POST -d '{hello: "there"}' http://localhost/test
```

And the [server] output is only:

``` console
calling onJson
```

**Comment by cainus** [comment]
That should automatically 400 for you, because the json is bad... try this instead: 

``` javascript
{"hello":"there"}.
```

When I tried your test with the bad json, I got this automatic response: 

``` javascript
{"error":{"type":400,"message":"Bad Request","detail":"invalid json."}}
```

`req.onJson` doesn't return if it handles the response for you.

Do you see the same over there?  Thanks for your patience, by the way... Works had me really busy with other stuff lately.

**Comment by disruptek** [comment]
I see that too.  Under what circumstances does the callback get invoked with a non-`null` error argument?

I expected an opportunity to handle a JSON parsing error.  The current behavior means that I have to worry about cleaning up any resources before I invoke `onJson`, because control may never return to my codepath, right?

**Comment by cainus** [comment]
Yeah that's what it means.  What sort of clean-up would you be worried about?

Obviously I should document this better at the very least.  :)

**Comment by disruptek** [comment]
Arguably, if there was no reason to clean anything up, then there'd be no reason not to pre-parse the input and supply it as an additional argument, say, when the developer specified a handler function of arity three.

edit: Okay, we might want to produce a response without parsing the input, but still...

If user authentication involves allocating database resources, for example, then we can't use those resources when attempting to log a JSON parse error.

It's not a hard problem to work around, as I can just do the parsing myself.  I'm just trying to understand when the `error` variable has truthy value; without knowing that, it's completely pointless.

Are there other failures of `onJson` which similarly short-circuit out of the handler?

**Comment by cainus** [comment]
It'll also short-circuit if you supply it a json-schema and the input doesn't match the schema, but you're not doing that.  See the second example here:  http://percolatorjs.com/documentation.html#req-onJson .

You're right that this processing could happen before the handler function gets hit, but I wanted to give the developer a way to specify which routes it should happen on, and a possible schema if desired.  I almost never use this without a schema, because the schema does a bunch of input validation for me automatically.

You could just use https://github.com/expressjs/body-parser if you want to parse the json in advance before all routes and don't want to use a json schema.

When I originally wrote this api, I didn't have a scenario where I returned an error, but I wanted to have the placeholder there in case a scenario developed (especially because that's the node convention)... But I can safely say that in the 2 years I've been using this, I can't think of an error-scenario that could ever occur where that error parameter would get a value.  

In the next version I'll probably remove that error parameter entirely, and do the parsing in advance.  I'd still have a helper function like this for the schema stuff though, because I get a lot of mileage out of that.

Does that make sense?  I appreciate the feedback BTW...

**Comment by disruptek** [comment]
Okay, cool.  I can see scenarios when we might want to do some in-handler work before we parse the input, and your use-cases make the design choices more clear.

I do still think it's odd to issue a response (essentially) in `onJson`, and I feel like even setting `error` to the automatically-constructed JSON response object would be an improvement that would be easy for the user to retrofit, and it would afford the user an opportunity to change the HTTP status code or extend the object.  This seems especially relevant given that schema validation errors may result from dynamically-generated schemas (based on user data, for example).

Just my opinion.  :-)

**Comment by cainus** [comment]
Even in that case onJson would 500 for you, as would be the proper response I think (it's an internal server error if you give onJson bad schemas).  `onJson` is really just to remove the tedium of json parsing, schema validation, and the error-reporting that we run into on basically every POST or PUT... If you need something more custom than what it does, you can definitely go without it.  

To be honest though I'm thinking about adding the body-parser middleware to percolator anyway, because I think it's probably prudent to force the body buffering to be up-front, rather than having it in onJson where the developer can wait way too long to call it (it is a stream handler afterall).  What do you think?

**Comment by disruptek** [comment]
I don't know enough about the internals to comment on the downside of waiting to read the input stream (though I'd like to hear more), but what about a scenario in which the customer is attempting to upload a large piece of content that is "too large to accept"?  We might not want to waste resources (ours or the customer's) reading it when we can check the Content-Length and reject the request immediately.

**Comment by cainus** [comment]
Well body-parser does the Content-Length check for you.  I'd have to set a reasonable default and then expose a config variable in the constructor option to keep everything backward compatible.  Currently I don't have that check at all, so I think that seals the deal.  This will probably solve your other issue as well, if I understand it correctly.  I _think_ your setTimeout is delaying the onJson enough that the response body is no longer available.   I'll try it later today and get back to you.

**Comment by disruptek** [comment]
That was an arbitrary example -- we might want to reject the request for any reason.  Maybe this user (or this resource) is limited in terms of content body size.  In the current implementation, I can evaluate the authenticated user and the headers before I commit to reading the input.  Perhaps a hook that can be overridden here would be appropriate instead of narrowly defining a global input-size-limit default?  It's getting complex, because one might argue that each handler may wish to act differently.

What are the downsides of delaying a read of the input stream?  I'm not clear on why the "response [request?] body is no longer available".

Unfortunately, in my case I'm waiting on asynchronous operations outside my control when authenticating requests, so I'm not able to create a synchronous `authenticate()`.
